[workspace]
resolver = "3"
members = [
    "nostr_options_cli",
    "crates/*"
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.91.0"
authors = ["DistributedLab"]
readme = "Readme.md"


[workspace.dependencies]
anyhow = { version = "1.0.100" }
clap = { version = "4.5.49", features = ["derive"] }
config = { version = "0.15.16", default-features = true }
dotenvy = { version = "0.15" }
global_utils = { path = "./crates/global_utils" }
hex = { version = "0.4.3" }
itertools = { version = "0.14.0" }
reqwest = { version = "0.12.23", features = ["blocking", "json"] }
ring = { version = "0.17.14" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145" }
sha2 = { version = "0.10.9", features = ["compress"] }
simplicity-lang = { version = "0.5.0" }
simplicityhl = { version = "0.2.0", features = ["serde"] }
simplicityhl-core = { version = "0.1.1" }
state_change_types = { path = "./crates/state_change_types" }
thiserror = { version = "2.0.17" }
tracing = { version = "0.1.41" }
tracing-appender = { version = "0.2.3" }
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
nostr = { version = "0.43.1" }
tokio-tungstenite = { version = "0.28.0", features = ["native-tls"] }
futures-util = "0.3.31"
tokio = {version =  "1.48.0", features = ["full"] }

